[versions]
agp = "8.6.0"
kotlin = "2.0.0"
coreKtx = "1.13.1"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.9.3"
constraintlayout = "2.1.4"
org-jetbrains-kotlin-android = "1.8.0"
navigation-fragment-ktx = "2.5.3"
navigation-ui-ktx = "2.5.3"
leanback = "1.0.0"
retrofitVersion = "2.9.0"
retrofitJsonVersion = "2.9.0"
moshiRetrofit = "2.9.0"
interceptorLoggin = "4.9.3"
navigation-plugin = "2.7.1"
coil-compose = "1.4.0"
kotlin-parecelize = "2.1.0-RC2"
camera-x = "1.5.0-alpha03"
tensorflow-lite = "0.0.0-nightly-SNAPSHOT"
tensorflow-lite-support = "0.1.0"
compose-ui = "1.6.4"
material2 = "1.6.4"
material3 = "1.2.1"
foundation = "1.6.4"
tooling = "1.6.4"
activity-compose = "1.10.0"
viewmodel-compose = "2.8.5"
livedata = "1.6.4"
rxjava2 = "1.6.4"
adaptive = "1.0.0-alpha04"
lifecycleRuntimeKtx = "2.9.0"
composeBom = "2024.09.00"
compose-k = "2.0.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation-fragment-ktx" }
navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation-ui-ktx" }
androidx-leanback = { group = "androidx.leanback", name = "leanback", version.ref = "leanback" }
retrofit = {group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofitVersion" }
retrofitJson = {group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofitJsonVersion" }
moshiRetrofit = {group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "moshiRetrofit" }
interceptorLoggin = {group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "interceptorLoggin" }
coil-compose = {group = "io.coil-kt", name = "coil-compose", version.ref = "coil-compose" }
cameraX-core = {group = "androidx.camera", name = "camera-core", version.ref = "camera-x" }
cameraX-camera2 = {group = "androidx.camera", name = "camera-camera2", version.ref = "camera-x" }
cameraX-lifecicle = {group = "androidx.camera", name = "camera-lifecycle", version.ref = "camera-x" }
cameraX-view = {group = "androidx.camera", name = "camera-view", version.ref = "camera-x" }
tensorflow-lite = {group = "org.tensorflow", name = "tensorflow-lite", version.ref = "tensorflow-lite"}
tensorflow-lite-sopport = {group = "org.tensorflow", name = "tensorflow-lite-support", version.ref = "tensorflow-lite-support"}

#jetpack compose

compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose-ui" }
compose-ui-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "tooling" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "tooling" }
compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "compose-ui" }
compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "compose-ui" }

material2 = { group = "androidx.compose.material", name = "material", version.ref = "material2" }
material-icons-core = { group = "androidx.compose.material", name = "material-icons-core", version.ref = "material2" }
material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "material2" }

material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
material3-adaptive = { group = "androidx.compose.material3.adaptive", name = "adaptive", version.ref = "adaptive" }

foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "foundation" }

activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "viewmodel-compose" }
runtime-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata", version.ref = "livedata" }
runtime-rxjava2 = { group = "androidx.compose.runtime", name = "runtime-rxjava2", version.ref = "rxjava2" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "org-jetbrains-kotlin-android" }
org-jetbrains-kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "org-jetbrains-kotlin-android" }
navigation-safe = { id = "androidx.navigation.safeargs", version.ref = "navigation-plugin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin-parecelize"}
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "compose-k" }

